name: PHP Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: Install Composer dependencies
        run: composer install --no-dev --optimize-autoloader

      - name: Install PHPUnit
        run: composer global require phpunit/phpunit

      - name: Add Composer's bin directory to PATH
        run: echo "$(composer config --global home)/vendor/bin" >> $GITHUB_PATH
  
      - name: Run PHPUnit tests
        run: phpunit --configuration ./phpunit.xml
