name: PHP Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: Install Composer
        run: |
          curl -sS https://getcomposer.org/installer | php
          
      - name: Install dependencies
        run: composer install --no-dev --optimize-autoloader  # Instala as dependências do PHP

      - name: Install PHPUnit
        run: composer global require phpunit/phpunit
  
      - name: Add Composer's bin directory to PATH
        run: echo "::add-path::$(composer config --global home)/vendor/bin"
  
      - name: Run PHPUnit tests
        run: phpunit --configuration ./phpunit.xml

      - name: Deploy
        run: |
          ssh user@server "cd /path/to/your/project && git pull origin main && composer install --no-dev --optimize-autoloader && php artisan migrate --force"
